using System.Collections;
using System.Collections.Generic;
using UnityEngine;

public class Equipment : MonoBehaviour
{
    DelverzTile currentEquipment;

    /*public bool CanMove(Bounds moveBounds)
    {
        //return currentEquipment.CanMove(boundsToTest);
    } */
}


public class SwordTile: DelverzTile
{
    [SerializeField] private GameObject swordNorth, swordEast, swordSouth, swordWest;

    public void SpawnEquipment(Vector3 spawnDirection)
    {
        //if it's this direction turn on this gameobject
        //my collider equals the one on this gameobject
        //my bounds equals the one generated by that collider
        //check if I can 
    }
}

public class ShieldTile : DelverzTile
{
    [SerializeField] private GameObject shieldNorth, shieldEast, shieldSouth, shieldWest;
}