using System.Collections;
using System.Collections.Generic;
using Unity.VisualScripting;
using UnityEngine;
using UnityEngine.Tilemaps;

public enum ColliderType
{
    player,
    wall,
    projectile,
    ground,
    groundObject,
    air,
    sword,
    bat
}

public struct TileIntersect
{
    public bool canTraverse;
    public List<DelverzTile> tilesToTrigger;
}

public class GridManager : MonoBehaviour
{
    public static GridManager current;

    public static Tilemap tilemap;

    static Dictionary<Bounds, DelverzTile> tileDictionaryLayer1 = new Dictionary<Bounds, DelverzTile>();
    static Dictionary<Bounds, DelverzTile> tileDictionaryLayer2 = new Dictionary<Bounds, DelverzTile>();
    static Dictionary<Bounds, DelverzTile> tileDictionaryLayer3 = new Dictionary<Bounds, DelverzTile>();
    static Dictionary<Bounds, DelverzTile> tileDictionaryLayer4 = new Dictionary<Bounds, DelverzTile>();
    static Dictionary<Bounds, DelverzTile> tileDictionaryLayer5 = new Dictionary<Bounds, DelverzTile>();

    private Dictionary<Bounds, DelverzTile>[] tileDictionaries = { tileDictionaryLayer1, tileDictionaryLayer2, tileDictionaryLayer3, tileDictionaryLayer4, tileDictionaryLayer5 };

    private void Awake()
    {
        current= this;
    }

    public void AddToTileDictionary (int tileLayer, Bounds tileBounds, DelverzTile tile)
    {
        tileDictionaries[tileLayer].Add (tileBounds, tile);
    }

    public void RemoveTileFromDictionary(int tileLayer, Bounds tileBounds)
    {
        tileDictionaries[tileLayer].Remove(tileBounds);
    }

    public TileIntersect ReturnIntersectTiles (Bounds moveBounds, DelverzTile myTile)
    {
        TileIntersect intersectData = new TileIntersect();
        intersectData.tilesToTrigger = new List<DelverzTile>();
        intersectData.canTraverse = true;

        //I'm aware that dictionaries is probably not the best use case for this anymore. It used to be. I haven't bothered to update it.

        //for each layer of the tile dictionary
        for (int i = 4; i >= 0; i--)
        {
            //if the bounding box generated by my vector contains a bounding box from this dictionary
            foreach (KeyValuePair<Bounds, DelverzTile> boundsY in tileDictionaries[i])
            {
                if (moveBounds.Intersects(boundsY.Key))
                {
                    DelverzTile tileIAmTraversingTo = boundsY.Value;
                    ColliderType otherColliderType = tileIAmTraversingTo.ReturnColliderType();
                    ColliderType myColliderType = myTile.ReturnColliderType();

                    //There's probably a better way to do this :(
                    //updating this is very annoying if things are changed or new collision types are added.

                    //--HARD COLLISIONS--
                    //-PLAYER-
                    //if I'm a player and incoming tile is a wall or a bat return hardcollisiom
                    if (myColliderType == ColliderType.player && (otherColliderType == ColliderType.wall || otherColliderType == ColliderType.bat)) { intersectData.canTraverse = false; return intersectData; }
                    //if I'm a player and incoming tile is a another player that isn't me return hardcollision
                    else if (myColliderType == ColliderType.player && (otherColliderType == ColliderType.player && tileIAmTraversingTo != myTile)) { intersectData.canTraverse = false; return intersectData; }
                    //-SWORD-
                    //if I'm a sword and incoming tile is a wall return hardcollision
                    else if (myColliderType == ColliderType.sword && otherColliderType == ColliderType.wall) { intersectData.canTraverse = false; return intersectData; }
                    //-BAT-
                    //If I'm a bat and incoming tile is a bat that isn't me return hardcollision
                    //If I'm a bat and incoming tils is a player or a wall return hardcollision

                    //--TRIGGERING COLLISIONS--
                    //-PLAYER-
                    //if I'm a player and incoming tile is a sword that isn't mine return triggering collision
                    else if (myColliderType == ColliderType.player && (otherColliderType == ColliderType.sword && tileIAmTraversingTo != myTile.ReturnSword())) { intersectData.tilesToTrigger.Add(boundsY.Value); }
                    //I'f I'm a player and incoming tile is a projectile or a groundObject return triggering collision
                    else if (myColliderType == ColliderType.player && (otherColliderType == ColliderType.projectile || otherColliderType == ColliderType.groundObject)) { intersectData.tilesToTrigger.Add(boundsY.Value); }
                    //-GROUNDOBJECT-
                    //if I'm a ground object and incoming tile is a player return triggering collision
                    else if (myColliderType == ColliderType.groundObject && otherColliderType == ColliderType.player && tileIAmTraversingTo != myTile) { intersectData.tilesToTrigger.Add(boundsY.Value); }
                    //-SWORD-
                    //if I'm a sword and incoming tile is a sword that isn't me return triggering collision
                    else if (myColliderType == ColliderType.sword && (otherColliderType == ColliderType.sword && tileIAmTraversingTo != myTile)) { intersectData.tilesToTrigger.Add(boundsY.Value); }
                    //if I'm a sword and incoming tile is a player that isn't mine return triggering collision
                    else if (myColliderType == ColliderType.sword && (otherColliderType == ColliderType.player && tileIAmTraversingTo != myTile.ReturnPlayer())) { intersectData.tilesToTrigger.Add(boundsY.Value); }
                    //if I'm a sword and incoming tile is a projectile return triggering collision
                    else if (myColliderType == ColliderType.sword && otherColliderType == ColliderType.projectile) { intersectData.tilesToTrigger.Add(boundsY.Value); }
                    //-PROJECTILE-
                    //if I'm a projectile and incoming tile is a projectile that isn't me return triggeringcollision
                    else if (myColliderType == ColliderType.projectile && otherColliderType == ColliderType.projectile && tileIAmTraversingTo != myTile) { intersectData.tilesToTrigger.Add(boundsY.Value); }
                    //if I'm a projectile and incoming tile is a player or a wall or a sword return triggeringcollision
                    else if (myColliderType == ColliderType.projectile && (otherColliderType == ColliderType.sword || otherColliderType == ColliderType.wall || otherColliderType == ColliderType.player)) { intersectData.tilesToTrigger.Add(boundsY.Value); }
                }
            }
        }
        return intersectData;
    }

    public void SetGroundOnFireInRadius(float explosionRadius)
    {
        //for each piece of ground
        foreach(KeyValuePair<Bounds, DelverzTile> boundsY in tileDictionaries[0])
        {

        }

        //set it on fire if it's within this radius
    }
}
